apiVersion: apps/v1
kind: Deployment
metadata:
  name: merc
spec:
  replicas: 8
  selector:
    matchLabels:
      app: merc
  template:
    metadata:
      labels:
        app: merc
    spec:
      containers:
      - name: merc
        image: piyushdev0325/online_shop_mercedes:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

